
export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    flex: 1,
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];

export const rows = [
  {
    id: 1,
    name: "sanae ",
    email: "sanae@gmail.com",
    age: 35,
    phone: "0600000000",
    address: "0912  ",
    city: "casablanca",
    zipCode: "12000",
    registrarId: 1,
  },
  {
    id: 2,
    name: "sara",
    email: "sara@gmail.com",
    age: 42,
    phone: "0600000000",
    address: "1234 ",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 2,
  },
  {
    id: 3,
    name: "Meryem",
    email: "Meryem@gmail.com",
    age: 45,
    phone: "0600000000",
    address: "3333",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 3,
  },
  {
    id: 4,
    name: "Aya",
    email: "Aya@gmail.com",
    age: 16,
    phone: "0600000000",
    address: "10000",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 4,
  },
  {
    id: 5,
    name: "amina",
    email: "amina@gmail.com",
    age: 31,
    phone: "0600000000",
    address: "10000 ",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 5,
  },
  {
    id: 6,
    name: "asmae",
    email: "asmae@gmail.com",
    age: 150,
    phone: "0600000000",
    address: "1234 ",
    city: "casablanca",
    zipCode: "10001",
    registrarId: 6,
  },
  {
    id: 7,
    name: "imane",
    email: "imane@gmail.com",
    age: 44,
    phone: "0600000000",
    address: "22215",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 7,
  },
  {
    id: 8,
    name: "imane",
    email: "imane@gmail.com",
    age: 36,
    phone: "0600000000",
    address: "4123",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 8,
  },
  {
    id: 9,
    name: "imane",
    email: "imane@gmail.com",
    age: 65,
    phone: "0600000000",
    address: "51234",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 9,
  },
  {
    id: 10,
    name: "imane",
    email: "imane@gmail.com",
    age: 42,
    phone: "0600000000",
    address: "4123",
    city: "casablanca",
    zipCode: "10000",
    registrarId: 10,
  },

];


